apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: postgresql
data:
  POSTGRES_DB: "digital_twin"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "Abcd1234"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init-config
  namespace: postgresql
data:
  init.sql: |
    CREATE EXTENSION IF NOT EXISTS vector;
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
