apiVersion: v1
kind: Namespace
metadata:
  name: twinspring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-config
  namespace: twinspring
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
    listener 9001
    protocol websockets
    allow_anonymous true
    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout
