apiVersion: v1
kind: Service
metadata:
  name: mqtt-service
  namespace: mqtt
spec:
  type: NodePort
  ports:
  - port: 1883
    targetPort: 1883
    nodePort: 31883
    name: mqtt
  - port: 9001
    targetPort: 9001
    nodePort: 31901
    name: websocket
  selector:
    app: mqtt
