apiVersion: v1
kind: Namespace
metadata:
  name: twinspring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: twinspring
data:
  OLLAMA_BASE_URL: "http://ollama-service:11434"
  LLM_MODEL: "qwen2.5:14b"
  VECTOR_DB_HOST: "postgresql-service"
  VECTOR_DB_PORT: "5432"
  VECTOR_DB_NAME: "digital_twin"
  VECTOR_DB_USER: "postgres"
  VECTOR_DB_PASSWORD: "Abcd1234"
  INFLUX_URL: "http://influxdb-service:8086"
  INFLUX_TOKEN: "twinspring-influx-admin-token"
  INFLUX_ORG: "twinspring"
  INFLUX_BUCKET: "iot_data"
  SPRING_BASE_URL: "http://spring-service:8080"
