apiVersion: v1
kind: Namespace
metadata:
  name: twin-bim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bim-pv
spec:
  capacity:
    storage: 300Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/bim
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bim-pvc
  namespace: twin-bim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 300Gi
