apiVersion: v1
kind: Namespace
metadata:
  name: twin-detect
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: detect-config
  namespace: twin-detect
data:
  SPRING_URL: "http://spring-service.twin-spring.svc.cluster.local:8080"
  YOLO_MODEL: "yolov8n.pt"
