apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: twin-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
      - name: agent
        image: yeongjin95/twin-agent:latest
        ports:
        - containerPort: 7070
        envFrom:
        - configMapRef:
            name: agent-config
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 1Gi
        readinessProbe:
          tcpSocket:
            port: 7070
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 7070
          initialDelaySeconds: 40
          periodSeconds: 20
