apiVersion: v1
kind: Namespace
metadata:
  name: twinspring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  namespace: twinspring
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql-service:5432/digital_twin"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "Abcd1234"
  MQTT_BROKER_URL: "tcp://mqtt-service:1883"
  MQTT_TOPIC: "test/topic"
  BIM_SERVER_URL: "http://bim-service:5112"
  AGENT_URL: "http://agent-service:7070"
  DETECT_URL: "http://detect-service:5001"
