apiVersion: apps/v1
kind: Deployment
metadata:
  name: bim
  namespace: twin-bim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bim
  template:
    metadata:
      labels:
        app: bim
    spec:
      containers:
      - name: bim
        image: yeongjin95/twin-bim:106
        ports:
        - containerPort: 5112
        envFrom:
        - configMapRef:
            name: bim-config
        volumeMounts:
        - name: bim-data
          mountPath: /app/data
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          tcpSocket:
            port: 5112
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5112
          initialDelaySeconds: 40
          periodSeconds: 20
      volumes:
      - name: bim-data
        persistentVolumeClaim:
          claimName: bim-pvc
