initContainers:
  - name: fix-permissions
    image: busybox:latest
    command:
      - sh
      - -c
      - |
        chown -R 1000:1000 /home/postgres/pgdata/data && chmod -R 700 /home/postgres/pgdata/data        
        CONF_FILE="/home/postgres/pgdata/data/postgresql.conf"
        if [ -f "$CONF_FILE" ]; then
          if ! grep -q "shared_preload_libraries" "$CONF_FILE"; then
            echo "shared_preload_libraries = 'timescaledb'" >> "$CONF_FILE"
          fi
        fi
    securityContext:
      runAsUser: 0
    volumeMounts:
      - name: postgresql-data
        mountPath: /home/postgres/pgdata/data