apiVersion: v1
kind: Namespace
metadata:
  name: twinspring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bim-config
  namespace: twinspring
data:
  ConnectionStrings__PostgreSQLConnection: "Host=postgresql-service;Port=5432;Database=digital_twin;Username=postgres;Password=Abcd1234;"
  ASPNETCORE_URLS: "http://+:5112"
